計算機プログラムの作成
m-miwa1/calc pull request #3
Opened 2020-09-07 08:28 UTC by m-miwa1

研修で作成した計算機プログラムのコードレビューをお願いします。
ファイルは三つあり、
calc1.html
calc2.php
calc3.php
になっています。
empty.txtはプルリクエストのために作成した空のテキストファイルです。

2020-09-07 08:48 UTC, k-morita-b commented
ファイル名がよろしくありません。
何のファイルかわかるように命名したほうがよいです。
例えばですが、結果画面ならば result.php など。

2020-09-07 08:52 UTC, y-tokui commented
好みかもしれませんが
・calc2.php　→ question.php
・calc3.php　→ answer.php

などにした方がファイル名が分かりやすかったんじゃないかなと思いました。
※ファイル名変更すると差分が分からなくなると思うので、今回は修正しなくていいと思います。

2020-09-07 08:55 UTC, y-tokui reviewed
今回はPR作成用にコミットしたと思うので、仕方ないと思いますが、
案件に入ってから、コミットメッセージも分かりやすいようにして頂きたいです。

2020-09-07 08:55 UTC, y-tokui commented on calc2.php
> +        }
$randGit = 9;
$randGit = 99;

定数なので、constの方が良いと思いました。

2020-09-07 09:10 UTC, y-tokui reviewed
何件かコメントしました。
ご確認よろしくお願いします。

2020-09-07 09:10 UTC, y-tokui commented on calc3.php
> +        $arrayAnswer = unserialize($_POST['arrayAnswer']);
全体的にコメントがシンプルで分かりやすく、
すごくコードを読みやすかったです！！

2020-09-07 09:10 UTC, y-tokui commented on calc2.php
> +            $randGit = 9;
$strDigitKeyword = "0-9";
は不要では？と思いました。
範囲の変更があった時に、修正箇所が増えてしまうと思いました。
（ないかもしれませんが0~7に変更されるなど...）
$randGit = 9;
があるので、こちらを使用すればいいような気がします。

2020-09-07 09:14 UTC, y-tokui commented on calc3.php
> +        <?php if ($arrayInputAnswer[$n] == $arrayAnswer[$n]) : ?>
厳密評価の方が良いかなと思います。
https://www.php.net/manual/ja/types.comparisons.php

2020-09-07 09:32 UTC, k-morita-b commented on calc1.html
> +        <input type="radio" name="intDigit" value="1" required>0-9まで<br>
問題ではないのですが、requiredよりもcheckedのほうが良い気がしますがいかがでしょうか？
＜理由＞
requiredでは初期チェックが入らず、「必須」の文言があればよいが、なければ必須である旨ユーザがわからず、
ユーザビリティ的に良くないかと思いました。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +?>
ロジックと表示部分は明確に切り分けてください。
HTML内にphpでロジックを記載しているので、
phpでロジックを記載したあとに、htmlを記載してください。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +                $intCalcMethod += $intCalcs;
asの後ろの変数は一つを表すので s はいらないと思います。

これでもよいですが、array_sum()を使うとスッキリします。（そういうのもあるんだということだけわかってもらえれば大丈夫です。）

好みが分かれますが、三項演算子を使えば34行目から41行目までスッキリ書けるかなと思います。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +        if ($intDigit == 1) {
基本的に厳密比較の === のほうが良いかと思います。
（厳密比較で型まで判定します。）

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +            $arrayQuestionB[$x] = mt_rand(0,$randGit);
$arrayQuestionA[] = ~;
で配列に格納していけるはずです。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +        for ($x = 0; $x < 5; $x++) {
仕様にはないですが、現状は5問ですが、
可変性を考えると定数定義してしまったほうが良いかと思います。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +            $randGit = 99;
$randGitも定数定義したほうが良いかと思います。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +            $strDigitKeyword = "0-99";
最小値と最大値として定数定義してしまえば、様々な数値で対応できますね。

2020-09-07 09:32 UTC, k-morita-b commented on calc2.php
> +    <?php for ($o = 0; $o < 5; $o++) : ?>
$indexとかのほうがいいと思います。

2020-09-07 09:32 UTC, k-morita-b commented on calc3.php
> +
同じくロジックを切り出してください。

2020-09-08 02:12 UTC, m-miwa1 commented on calc2.php
> +        }
定数に修正しました。

2020-09-08 02:12 UTC, m-miwa1 commented on calc3.php
> +        $arrayAnswer = unserialize($_POST['arrayAnswer']);
ありがとうございます。
シンプルにしたほうが伝わりやすいと思うので心掛けています。

2020-09-08 02:13 UTC, m-miwa1 commented on calc2.php
> +            $randGit = 9;
$strDigitKeywordに関しては削除しました。
定数RANDDIGITを利用するように変更しました。

2020-09-08 02:16 UTC, m-miwa1 commented on calc1.html
> +        <input type="radio" name="intDigit" value="1" required>0-9まで<br>
前提知識を知らない人も利用する想定をしていなかったです。
実務ではそういった考えは非常に大切だと思うので、忘れないようにします。
当該の部分はcheckedに変更しました。

2020-09-08 02:16 UTC, m-miwa1 commented on calc2.php
> +?>
phpとhtmlを切り離しました。

2020-09-08 02:17 UTC, m-miwa1 commented on calc2.php
> +                $intCalcMethod += $intCalcs;
わかりにくいのでintCalcsからintCalcに変更しました。
array_sum()や三項演算子については適宜使っていこうと思います。

2020-09-08 02:18 UTC, m-miwa1 commented on calc2.php
> +            $arrayQuestionB[$x] = mt_rand(0,$randGit);
いただいた表記通りに変更しました。

2020-09-08 02:19 UTC, m-miwa1 commented on calc2.php
> +            $randGit = 99;
定数RANDIGITに変更しました。

2020-09-08 02:19 UTC, m-miwa1 commented on calc2.php
> +            $strDigitKeyword = "0-99";
問題の最小値として定数ONEDIGITを追加しました。
問題の最大値はRANDDIGITで代用しました。

2020-09-08 02:20 UTC, m-miwa1 commented on calc2.php
> +    <?php for ($o = 0; $o < 5; $o++) : ?>
$indexに変更しました。

2020-09-08 02:20 UTC, m-miwa1 commented on calc3.php
> +
phpとhtmlを切り離しました。

2020-09-08 02:22 UTC, m-miwa1 commented
お二人からファイル名についてのご指摘がありましたが、これからはファイル名もわかりやすく命名します。
ご指摘にあった通り、ファイル名を修正すると差分がわからなくなってしまうので、今回はこのまま進めさせていただきます。

2020-09-08 02:27 UTC, m-miwa1 commented on calc2.php
> +        if ($intDigit == 1) {
こちらですが厳密評価に変更すると正しく分岐しない(どの値でもelseに進む)ようになってしまいました。
$_POSTで取り出す際に型が文字列に変わってしまっているからだと思われます。
現状ではそのままにしていますが、$_POSTから取り出す際にintに型変換したほうがいいのでしょうか？

2020-09-08 02:27 UTC, m-miwa1 commented on calc3.php
> +        <?php if ($arrayInputAnswer[$n] == $arrayAnswer[$n]) : ?>
こちらですが厳密評価に変更すると正しく分岐しない(どの値でもelseに進む)ようになってしまいました。
$_POSTで取り出す際に型が文字列に変わってしまっているからだと思われます。
現状ではそのままにしていますが、$_POSTから取り出す際にintに型変換したほうがいいのでしょうか？

2020-09-08 02:35 UTC, m-miwa1 commented on calc2.php
> +        for ($x = 0; $x < 5; $x++) {
問題の出題数として定数NUMBERQUESTIONを定義しました。

2020-09-08 02:56 UTC, m-miwa1 commented
修正後プッシュした際に作業用にコメントアウトしたものが削除できていなかったので、再度プッシュしました。

2020-09-08 07:34 UTC, yukiokunobtm commented on calc2.php
> +
定数がファイル内でバラバラに定義されています。定数を定義する際は一か所にまとめて定義する方が可読性・修正のしやすさ共に向上します。
const.php等、新しい定数用のファイルを作成し、そこで定義してくあげてください。

2020-09-08 08:10 UTC, k-morita-b commented on calc2.php
> +        if ($intDigit == 1) {
そのままでも問題ないかと思いますが、個人的には明示的にintに変換します。
命名にも int と入っているので。

2020-09-08 08:10 UTC, k-morita-b commented on calc2.php
> +            define('RANDDIGIT', '99');
不要なコメントアウトは削除しましょう。

また、奥野さんレビューにある通り、定数定義はまとめて行っていただきたいのですが、
必要なものはあらかじめ定数定義して、
使う定数を出し分けるほうが良いと思います。
（条件分岐内で定数定義するのではなく、使い分けるという感じです。）

ぼくならばですが、定数定義時に配列などで定義して、$intDigitの値で使う定数を出し分けます。

2020-09-08 08:10 UTC, k-morita-b commented on calc3.php
> +<?php endfor; ?>
ぼくならばですが、
このあたりの回答部分もロジック側で判定して回答を作成し、
表示側では配列をforeachで回すだけにします。
多少、ロジックと表示が混在するので可読性の問題かなと思います。

2020-09-08 08:36 UTC, k-morita-b commented on calc1.html
> +        <input type="radio" name="intDigit" value="1" required>0-9まで<br>
確認しました。

2020-09-08 08:51 UTC, k-morita-b requested changes

2020-09-08 08:51 UTC, k-morita-b commented on calc3.php
> +</html>
テストです。

2020-09-08 09:12 UTC, m-miwa1 commented on calc3.php
> +<?php endfor; ?>
問題と解答と正誤を格納する配列を追加し、さらにロジックと表示を切り離しました。

2020-09-08 09:16 UTC, m-miwa1 commented on calc2.php
> +            define('RANDDIGIT', '99');
別ファイルにてdefine('MAX_DIGIT', [9,99])と定義し、MAX_DIGIT[0]とMAX_DIGIT[1]で使い分けていくという方法でいいのでしょうか？
また、この問題の最大値9 or 99をフォームのvalueで直接指定し、calc2.php内で変数や定数に$_POSTから取り出し格納するといった方法はいけないのでしょうか？

2020-09-08 10:28 UTC, yukiokunobtm commented on calc2.php
> +<!-- 計算機　表示された問題の解答を入力し、送信する画面 -->
処理のPHPの開始タグの前には何も書かないようにしましょう。
コーディング規約に関してはこちら参考にどうぞ。
http://www.infiniteloop.co.jp/docs/psr/psr-2-coding-style-guide.html

2020-09-09 01:12 UTC, yukiokunobtm commented on calc2.php
> +	//前画面からPOSTで値が飛んできていない場合は何も表示しない
インデントに半角スペースとタブ文字が混ざってるので半角スペースに統一しましょう。

2020-09-09 01:12 UTC, yukiokunobtm commented on calc2.php
>      if (!empty($_POST["intDigit"])) :
ifの範囲が大きくなってしまているのでexitとかで終了した方がすっきりするかと思います。(早期リターン?)
個人的にif (~~) :　が利用されているのはあまり見ないので中括弧でくくって上げる方がいいかなと思います。
好みかもしれませんが。。

2020-09-09 01:27 UTC, m-miwa1 commented on calc2.php
> +
定数を定義したファイルconst.phpを追加しました。

2020-09-09 01:28 UTC, m-miwa1 commented on calc2.php
> +            define('RANDDIGIT', '99');
define('MAX_DIGIT', [1 => 9, 2 => 99]);　という形に変更し、フォームから来た値をそのまま利用できるように変更しました。

2020-09-09 01:29 UTC, m-miwa1 commented on calc2.php
> +<!-- 計算機　表示された問題の解答を入力し、送信する画面 -->
PSR-2に準拠した形に変更しました。

2020-09-09 02:07 UTC, y-tokui commented on calc3.php
> +        <?php if ($arrayInputAnswer[$n] == $arrayAnswer[$n]) : ?>
そうなんですね。intで渡ってきていると思っていました。
このままで問題ないと思います！

2020-09-09 02:10 UTC, m-miwa1 commented on calc2.php
>      if (!empty($_POST["intDigit"])) :
値が飛んできていない場合exitで終了するように修正しました。
if (~~) :はあまり使われないんですね。勉強になりました。

2020-09-09 02:10 UTC, m-miwa1 commented on calc2.php
> +	//前画面からPOSTで値が飛んできていない場合は何も表示しない
修正しました。

2020-09-09 02:16 UTC, k-morita-b commented on calc2.php
> +            define('RANDDIGIT', '99');
配列などでとお伝えしましたが、今回は2つだけなので普通に定数定義してしまっても大丈夫です。
※配列での定数定義はphp7系以降しか使えませんが、連想配列の形で定義してしまいます。
　difine('MAX_DIGIT_LIST', ['DIGIT_9' => 9, 'DIGIT_99' => 99])
   で$intDigitが 0 のときに DIGIT_9 を呼ぶ形です。
※enumとか使うとより管理しやすいかなと思います。また調べておいていただければ。

> この問題の最大値9 or 99をフォームのvalueで直接指定し、calc2.php内で変数や定数に$_POSTから取り出し格納する
書き換えられるもの、かつ今回はいろんな部分（表示やロジック）で使う値なので、
そのまま使うのは良くないかなと思っています。

2020-09-09 02:21 UTC, m-miwa1 commented on calc2.php
> +        if ($intDigit == 1) {
こちらのifを削除し、intDigitは定数内で使うことになりました。
命名と型の一致については意識します。

2020-09-09 02:25 UTC, m-miwa1 commented on calc2.php
> +            define('RANDDIGIT', '99');
返信ありがとうございます。
enumについてはまた勉強します。
フォームの値を直接使うのこともケースバイケースかと思われますが控えようと思います。

2020-09-09 02:45 UTC, k-morita-b approved these changes

2020-09-09 02:48 UTC, y-tokui approved these changes

2020-09-09 04:15 UTC, yukiokunobtm commented on const.php
> +?>
細かいことですがファイル全体のコードがphpのみの場合は終了タグは省略しましょう。

2020-09-09 04:28 UTC, yukiokunobtm commented on calc2.php
> +        require_once('const.php');
処理としては問題ないのですが、ファイルの呼び出しは処理の途中ではなく最初に書いてあげた方が自然です。

2020-09-09 04:33 UTC, m-miwa1 commented on const.php
> +?>
PSR-2を読んでいたのに消し忘れていました。
気を付けます。

2020-09-09 04:33 UTC, m-miwa1 commented on calc2.php
> +        require_once('const.php');
当該部分を修正しました。

2020-09-09 04:50 UTC, yukiokunobtm approved these changes

2020-09-09 05:49 UTC, btm-a-seki commented on calc2.php
> +if (empty($_POST["intDigit"])) {
POSTで値が送信されていないことを判定する構文としては不適切です。
このままではNoticeエラーが発生します。
値が送信されていない場合は、そもそも定義されていないため`!isset($_POST["intDigit"])`が適切でしょう。

2020-09-09 05:49 UTC, btm-a-seki commented on calc2.php
> +if (empty($_POST['intCalcMethod'])) {
チェックボックスの配列で何もチェックされていない場合は、値が送信されません。
つまり`intCalcMethod`が定義されないため、この構文だとNoticeエラーが発生します。
こちらも`!isset($_POST['intCalcmethod'])`で判定する方が適切でしょう。

2020-09-09 05:49 UTC, btm-a-seki commented on calc3.php
> +    }
出来上がる配列のイメージが以下だとした場合、このままでは恐らく意図しない配列の形になっているかと思います。
```php
$arrayQuestionAndAnswer = [
    0 => '1問目1 + 2 = 3...正解<br>',
    1 => '2問目1 + 2 = 3...正解<br>',
    2 => '3問目1 + 2 = 3...正解<br>',
    3 => '4問目1 + 2 = 3...正解<br>',
    4 => '5問目1 + 2 = 3...正解<br>',
]
```
この構文だと以下のような配列になります。
```php
$arrayQuestionAndAnswer = [
    0 => '1問目1 + 2 = 3',
    1 => '...正解<br>',
    2 => '2問目1 + 2 = 3',
    3 => '...正解<br>',
    4 => '3問目1 + 2 = 3',
    5 => '...正解<br>',
    6 => '4問目1 + 2 = 3',
    7 => '...正解<br>',
    8 => '5問目1 + 2 = 3',
    9 => '...正解<br>',
];
```
結果として、出力は問題無いように見えますが、
意図しているデータの構造が正しく作れているかどうかの確認を怠らないようにしてください。

2020-09-09 05:49 UTC, btm-a-seki commented on calc3.php
> +<?php echo $questionAndAnswer ?>
POSTで受け取った値を未加工のまま出力するのは危険です。
こういった場合こそ、htmlspecialcharsでエスケープしてください。

2020-09-09 06:19 UTC, m-miwa1 commented on calc2.php
> +if (empty($_POST["intDigit"])) {
isset関数を使った判定に変更しました。

2020-09-09 06:20 UTC, m-miwa1 commented on calc2.php
> +if (empty($_POST['intCalcMethod'])) {
isset関数を使った判定に変更しました。

2020-09-09 06:44 UTC, m-miwa1 commented on calc3.php
> +    }
これからは表示だけでなく内部のデータ構造等にも気を配ります。
当該部分は修正しました。

2020-09-09 06:44 UTC, m-miwa1 commented on calc3.php
> +<?php echo $questionAndAnswer ?>
htmlspecialchars関数を使用しました。

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
僕だったらPOSTされた変数は全て L7 でまとめてセットされているか確認した上で変数に入れますね。
その方がpostで渡ってきた値が全てチェックできているか漏れがないし、まとめてサニタイズもできるので。
```
if (!isset($_POST["intDigit"]) || !isset($_POST["intCalcmethod"])) {
    exit;
}

$intDigit = htmlspecialchars($_POST["intDigit"]);
$intCalcmethod = htmlspecialchars($_POST["intCalcmethod"]);

...
```

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc1.html
> +        <input type="checkbox" name="intCalcMethod[]" value="2">引き算
変数に型定義を入れるのはあまり一般的でないように思いますが Java では一般的なのでしょうか？
digit, calcMethod の方がシンプルでいい気がします

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
あとついでに `intCalcmethod` だと変数名が間違っているので常に条件分岐がfalseになる気がします

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +    }
ここの数字に `(足し算:1,引き算:2、その和が両方含む3)` のように意味を持たせると拡張性が低くなります。
ex. 例えば計算機の式に掛け算が含まれるとどう実装する？？

単純にそれぞれのパターンに対応する数値をconstで持っておく方がいいです。

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +    $arrayQuestionB[] = mt_rand(MIN_DIGIT,MAX_DIGIT[$intDigit]);
細かいですがカンマの後は半角スペースを空けましょう
`mt_rand(MIN_DIGIT, MAX_DIGIT[$intDigit]);`
また変数名がquestionとありますが、こちらは式で使うただの数字という認識なのでnumberなどのような変数名の方が適切かと思いました

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +    }
計算の種類で言うと「足し算」「引き算」「足し算と引き算」の3パターンになるのに、同列にif文が4つ並んでいる状態は好ましくないです。
僕が実装するなら以下のように3パターンに分けたのちに計算を表示します。
```
switch ($intCalcMethod) {
    case ADDITION:
        {足し算}
        break;
    case SUBSTRACTION:
        {引き算の処理}
        break;
    case ADDITION_SUBSTRACTION:
        {足し算と引き算のいずれかを生成する処理}
        break;
}
```
ついでに理想を言えば足し算・引き算を生成する処理は別メソッドにしてもいいですが、今回はOKです

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc3.php
> +}
POSTされた値をまとめてチェックするのがいいかと思いました

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc3.php
> +$arrayAnswer = unserialize($_POST['arrayAnswer']);
ここの段階でsanitizeしておきたいですね

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc3.php
> +for($n = 0; $n < 5; $n++){
5という値がマジックナンバーになってしまっています。
せめてconstのNUMBER_QUESTIONを使うかforeachで `$arrayQuestion` を回すような形のほうがいいと思いました
```
foreach ($arrayQuestion as $index => $question) {
    ...{中の処理}
}
```

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc1.html
> +        <input type="radio" name="intDigit" value="2">0-99まで
MAX_DIGITで定義されている値を使うべきかと感じました

2020-09-09 07:01 UTC, t-kawasaki-mgild commented on calc2.php
> +    } elseif (mt_rand(1,2) % 2 == 0) {
`mt_rand(1,2) % 2 == 0`
この条件分岐は他人が見たときに何を判断しているのかがよくわからないと思います。
したがって、以下のようなfunctionを定義するべきかと思いました。
```
function shouldOutputAddionFormula() {
    return mt_rand(1,2) % 2 == 0
}
...
elseif (shouldOutputAddionFormula) {
     {足し算を出力する処理}
}

```

2020-09-09 07:03 UTC, btm-a-seki commented on calc3.php
> +<?php echo $questionAndAnswer ?>
修正コメントの意図が正しく伝えられていなかったので詳細に解説します。
htmlspecialchars等でエスケープを行う場合は出力するタイミングで行ってください。
例えば、`echo htmlspecialchars($questionAndAnswer)`といった形ですね。
以下のサイトで詳しく説明してくれています。
https://qiita.com/rana_kualu/items/11cd41de5f0364ba2ee8#%E3%82%A8%E3%82%B9%E3%82%B1%E3%83%BC%E3%83%97

そうした場合、他にも修正が必要になってくる箇所が出てくると思います。
指摘された修正が他の箇所に影響していないか、他の箇所と辻褄があってるか等、
既存のプログラムの見直しも忘れないようにしてください。

2020-09-09 07:51 UTC, btm-a-seki commented on calc2.php
> +if (empty($_POST["intDigit"])) {
1点訂正。empty関数でも未定義の判定は可能でした。
ただし、`empty($_POST['intDigit'])`で`$_POST['intDigit'] = '0'`の場合でもtrueと判断されてしまうため、
issetのままで大丈夫です。

2020-09-09 08:16 UTC, m-miwa1 commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
こちらですがintCalcmethod（変数名calcMethodに変更）についてはフォームにて値を選択しないという場合がありますのでisset関数の対象にしてしまうと動作しなくなってしまいましたので、そのままにしてあります。

2020-09-09 08:20 UTC, m-miwa1 commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
htmlspecialchars関数についてもintDigit、intCalcmethod 、については直接HTMLに出力することが無いのですが必要なのでしょうか？
関さんから教えてもらったqiitaには
>そして、エスケープを行う場所は『PHPからPHPの外に出ていくその場所』です。　
とありましたので確認したいです。

2020-09-09 08:20 UTC, m-miwa1 commented on calc1.html
> +        <input type="checkbox" name="intCalcMethod[]" value="2">引き算
提案していただいた変数名に変更しました。

2020-09-09 08:21 UTC, m-miwa1 commented on calc2.php
> +    $arrayQuestionB[] = mt_rand(MIN_DIGIT,MAX_DIGIT[$intDigit]);
提案していただいた変数名に変更しました。
またmt_rand関数内のカンマ後に半角スペースを追加しました。

2020-09-09 08:57 UTC, m-miwa1 commented on calc3.php
> +for($n = 0; $n < 5; $n++){
こちらNUMBER_QUESTIONを使用する形で修正しました。

2020-09-09 09:02 UTC, m-miwa1 commented on calc3.php
> +}
empty関数をisset関数に置き換え、対象をPOSTで来る3つの値に変更しました。

2020-09-10 01:40 UTC, m-miwa1 commented on calc2.php
> +    } elseif (mt_rand(1,2) % 2 == 0) {
ランダムでbooleanの値を返すboolRandam関数を定義し、mt_rand関数と置き換えました。

2020-09-10 02:01 UTC, m-miwa1 commented on calc1.html
> +        <input type="radio" name="intDigit" value="2">0-99まで
calc1.htmlをcalc1.phpに変更し、当該部分と演算方法に定数を使用しました。

2020-09-10 02:39 UTC, m-miwa1 commented on calc2.php
> +    }
ifからswitchに変更しました。
問題と解答を生成する処理が同じことを何度も書いているので、引数で演算方法を変えられ、問題を生成する関数を定義したほうがよいと感じました。
次からは関数やクラスも搭載します。

2020-09-10 02:39 UTC, m-miwa1 commented on calc2.php
> +    }
演算方法を値に持つ連想配列CALC_METHODを追加しました。

2020-09-10 04:29 UTC, m-miwa1 commented on calc3.php
> +$arrayAnswer = unserialize($_POST['arrayAnswer']);
こちらのほうも　calc2.php L23-26 の質問と同様になります。

2020-09-10 04:32 UTC, m-miwa1 commented on calc2.php
> +if (empty($_POST["intDigit"])) {
ありがとうございます。emptyとissetの違いについても勉強になりました。

2020-09-10 04:40 UTC, m-miwa1 commented on calc3.php
> +<?php echo $questionAndAnswer ?>
echo内でエスケープを行うようにcalc3.phpを修正しました。

2020-09-10 05:22 UTC, btm-a-seki approved these changes

2020-09-10 05:23 UTC, btm-a-seki approved these changes

2020-09-10 09:57 UTC, t-kawasaki-mgild commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
> こちらですがintCalcmethod（変数名calcMethodに変更）についてはフォームにて値を選択しないという場合がありますのでisset関数の対象にしてしまうと動作しなくなってしまいましたので、そのままにしてあります

こちら把握しました

> htmlspecialchars関数についてもintDigit、intCalcmethod については直接HTMLに出力することが無いのですが必要なのでしょうか？

今回の対応ではないかもしれませんが、今後第3者が改修するときに必ずないとは言い切れないので入れておくのが無難かと思います

2020-09-10 10:16 UTC, t-kawasaki-mgild commented on calc2.php
> +        case "足し算引き算":
先日お伝えしたようにconst.phpで
```
define('ADDITION', 1);
define('SUBSTRACTION', 2);
define('ADDITION_SUBSTRACTION', 3);
```
のように定義して以下のようなswitch文にするべきかなと思います。
```
switch($calcMethod) {
    case ADDITION:
         ...
         break;
    case SUBSTRACTION:
         ....
         break;
    case ADDITION_SUBSTRATION:
        ...
        break;
}
```
日本語文字列を比較するのはあまり好ましくないです

2020-09-10 10:16 UTC, t-kawasaki-mgild commented on calc1.php
> +        <input type="checkbox" name="calcMethod[]" value="2"><?php echo CALC_METHOD[2] ?>
ここもお伝えしましたが
```
define('ADDITION', 1);
define('SUBSTRACTION', 2);
define('ADDITION_SUBSTRACTION', 3);
```
このように定義してこちらの値を使うべきかなと感じます。

2020-09-11 03:56 UTC, m-miwa1 commented on calc2.php
> +        case "足し算引き算":
すみません。少し理解が足りていませんでしたが、指摘をいただき理解できました。
定数ADDITION,SUBSTRACTION,ADDITION_SUBSTRATIONを追加し、switch内caseの値を変更しました。

2020-09-11 03:56 UTC, m-miwa1 commented on calc1.php
> +        <input type="checkbox" name="calcMethod[]" value="2"><?php echo CALC_METHOD[2] ?>
こちらもvalueの値を定数に変更しました。
echo CALC_METHOD[]は削除しました。

2020-09-11 07:22 UTC, m-miwa1 commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
変数digitにhtmlspecialchars関数を通すように変更しました。

2020-09-11 07:23 UTC, m-miwa1 commented on calc2.php
> +if (!isset($_POST['intCalcmethod'])) {
calcMethodについては足し算・引き算両方を選択した場合には配列として値がPOSTで来るようになっているのですが、htmlspecialchar関数は配列が通りませんでした。
これは中身をforで一つ一つhtmlspecialchar関数に通して別の配列に格納するといった方法でいいのでしょうか？

2020-09-14 02:59 UTC, t-kawasaki-mgild commented on calc2.php
> +    switch($calcMethod){
while (1) {
     $random = Math.random()
     if ($random % SUBSTRACTION === 0 && $calcMethod.includes(SUBSTRACTION)) {
         {引き算の処理}
         break;
    } else if ($random % ADDTION === 0 && $calcMethod.includes(ADDITION)) {
         {足し算の処理}
         break;
    } else if ($random % {掛け算} === 0 && $calcMethod.includes({掛け算})) {
         {掛け算の処理}
         break;
    }
}

2020-09-14 02:59 UTC, t-kawasaki-mgild commented on calc2.php
> +}
if (!isset($_POST['calcMethod'])) {
    $calcMethod = [ADDITION];
}

$calcMethod = [1]
$calcMethod = [2]
$calcMethod = [1, 2, 3]

2020-09-14 07:26 UTC, m-miwa1 commented on calc2.php
> +    switch($calcMethod){
こちらのコメントを参考に問題と解答を生成するメソッドを搭載しました。

2020-09-14 08:16 UTC, t-kawasaki-mgild approved these changes

2020-09-14 09:23 UTC, merged